In [4]:
import numpy as np

# Problem 1: Basic Array Element Comparisons
arr = np.array([2, 5, 8, 10, 3, 6, 7])
even_elements = arr[arr % 2 == 0]
print("Problem 1: Even Elements:", even_elements)

Problem 1: Even Elements: [ 2  8 10  6]


In [5]:
# Problem 2: Find Prime Array Elements
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

arr_prime = np.array([is_prime(x) for x in arr])
print("\nProblem 2: Prime Elements (True/False):", arr_prime)


Problem 2: Prime Elements (True/False): [ True  True False False  True False  True]


In [6]:
# Problem 3: Nested For Loops with 2D Arrays
n = 10
fib_matrix = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        if i == 0:
            fib_matrix[i, j] = j if j <= 1 else fib_matrix[i, j - 1] + fib_matrix[i, j - 2]
        else:
            fib_matrix[i, j] = fib_matrix[i - 1, j] + fib_matrix[i - 1, j - 1]

print("\nProblem 3: Fibonacci Matrix:")
print(fib_matrix)


Problem 3: Fibonacci Matrix:
[[   0    1    1    2    3    5    8   13   21   34]
 [  34    1    2    3    5    8   13   21   34   55]
 [  89   35    3    5    8   13   21   34   55   89]
 [ 178  124   38    8   13   21   34   55   89  144]
 [ 322  302  162   46   21   34   55   89  144  233]
 [ 555  624  464  208   67   55   89  144  233  377]
 [ 932 1179 1088  672  275  122  144  233  377  610]
 [1542 2111 2267 1760  947  397  266  377  610  987]
 [2529 3653 4378 4027 2707 1344  663  643  987 1597]
 [4126 6182 8031 8405 6734 4051 2007 1306 1630 2584]]


In [7]:
# Problem 4: While Loop Within a For Loop
arrays_list = [np.array([10, 20, 30, 40, 50]), np.array([5, 15, 25]), np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

for array in arrays_list:
    total_sum = 0
    index = 0
    while total_sum < 50 and index < len(array):
        total_sum += array[index]
        index += 1
    print("\nProblem 4: Sum and Index for Array", array)
    print("Sum:", total_sum)
    print("Index:", index)


Problem 4: Sum and Index for Array [10 20 30 40 50]
Sum: 60
Index: 3

Problem 4: Sum and Index for Array [ 5 15 25]
Sum: 45
Index: 3

Problem 4: Sum and Index for Array [1 2 3 4 5 6 7 8 9]
Sum: 45
Index: 9


In [8]:
# Problem 5: Logical Testing with NumPy
data = np.array([[5, 8, 3], [7, 2, 9], [6, 4, 1]])

row_indices, col_indices = np.where(data > 6)
locations = list(zip(row_indices, col_indices))
print("\nProblem 5: Locations of Elements Greater Than 6:")
print(locations)


Problem 5: Locations of Elements Greater Than 6:
[(0, 1), (1, 0), (1, 2)]
